import type { SourceSnapshot } from "@/lib/tfl/network-model/types"

/**
 * Inventory of each network-model record: where it comes from, where it is cached,
 * and how it refreshes. The Data model docs page renders this array directly.
 */
export const NETWORK_MODEL_STATUS: readonly SourceSnapshot[] = [
  {
    record: "Line",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "Name, colour, and mode for each line.",
    note: "Line identity, colour, and mode come from TfL line records shipped with tfl-ts.",
    sources: [{ label: "tfl-ts line metadata" }],
  },
  {
    record: "Station",
    classification: "process",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "A station’s identity and coordinates.",
    note: "NaPTAN ids and coordinates exist. Upgrade path: TfL station-data GTFS stops.txt for a stored station, platform, and OSM crosswalk.",
    sources: [
      { label: "tfl-ts STATION_HUBS" },
      {
        label: "TfL station-data GTFS",
        href: "https://api.tfl.gov.uk/stationdata/tfl-stationdata-gtfs.zip",
      },
    ],
  },
  {
    record: "StationHub",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "Stations that count as one interchange.",
    note: "Interchange grouping is already in STATION_HUBS. TfL station-data GTFS parent_station is the same id scheme.",
    sources: [
      { label: "tfl-ts STATION_HUBS" },
      {
        label: "TfL station-data GTFS",
        href: "https://api.tfl.gov.uk/stationdata/tfl-stationdata-gtfs.zip",
      },
    ],
  },
  {
    record: "ServicePattern",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "The ordered stations a service calls at.",
    note: "Ordered routes and service types ship as LINE_STATION_SEQUENCES.",
    sources: [{ label: "tfl-ts LINE_STATION_SEQUENCES" }],
  },
  {
    record: "PatternCall",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "One stop on a pattern, in order.",
    note: "Stop sequence is present on each static ordered route. Times are not stored here.",
    sources: [{ label: "tfl-ts LINE_STATION_SEQUENCES" }],
  },
  {
    record: "PatternCalendar",
    classification: "fetch",
    origin: "api-native",
    cachedIn: "none",
    refresh: "manual",
    coverage: "Underground, DLR, Tram, Cable Car",
    summary: "Which days a pattern runs. Not in the small map set yet.",
    note: "Present in the DfT BODS London GTFS (calendar.txt and calendar_dates.txt). Not ingested yet. Store a derived summary, not the dated trip list.",
    sources: [
      {
        label: "BODS London GTFS",
        href: "https://data.bus-data.dft.gov.uk/timetable/download/gtfs-file/london/",
      },
    ],
  },
  {
    record: "PatternCalendar",
    classification: "external",
    origin: "processed",
    cachedIn: "none",
    refresh: "n/a",
    coverage: "Elizabeth line, Overground",
    summary: "Not available for these lines yet.",
    note: "Absent from BODS and TfL station-data GTFS. Aubin/Transitous claims National Rail Enquiries coverage; that feed is unverified here. Fallback: UK2GTFS from ATOC CIF.",
    sources: [
      {
        label: "Aubin / Transitous GB GTFS",
        href: "https://beta.aubin.app/gtfs/great_britain_gtfs.zip",
      },
      {
        label: "Transitous GB sources",
        href: "https://transitous.org/sources-great-britain/",
      },
    ],
  },
  {
    record: "PatternFrequency",
    classification: "fetch",
    origin: "api-native",
    cachedIn: "none",
    refresh: "manual",
    coverage: "Underground, DLR, Tram, Cable Car",
    summary: "How often a pattern typically runs. Not in the small map set yet.",
    note: "Present in the BODS London GTFS (frequencies.txt). Collapse to headway bands per pattern and time window.",
    sources: [
      {
        label: "BODS London GTFS",
        href: "https://data.bus-data.dft.gov.uk/timetable/download/gtfs-file/london/",
      },
    ],
  },
  {
    record: "PatternFrequency",
    classification: "external",
    origin: "processed",
    cachedIn: "none",
    refresh: "n/a",
    coverage: "Elizabeth line, Overground",
    summary: "Not available for these lines yet.",
    note: "Same gap as PatternCalendar. Do not treat OSM relation count or ordered-route count as trains per hour.",
    sources: [
      {
        label: "Aubin / Transitous GB GTFS",
        href: "https://beta.aubin.app/gtfs/great_britain_gtfs.zip",
      },
    ],
  },
  {
    record: "PhysicalPath",
    classification: "process",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    coverage: "OSM unique-track (all rail modes)",
    summary: "Simplified track geometry for maps.",
    note: "Centreline, dual, and graph snapshots live under data/geography/unique-track. Rebuild with pnpm geography:unique-track. Default map paint is the preview LOD.",
    sources: [
      { label: "data/geography/ORIGIN.md" },
      { label: "Map – Tube & Rail (Geo)", href: "/docs/map-geographic" },
    ],
  },
  {
    record: "PhysicalPath",
    classification: "fetch",
    origin: "api-native",
    cachedIn: "none",
    refresh: "manual",
    coverage: "BODS shapes — Underground, DLR, Tram, Cable Car",
    summary: "Timetable-linked shapes exist; the map uses the simplified track set.",
    note: "Trip-linked shapes.txt exists in the BODS London GTFS. Use it to cross-check OSM, not to replace unique-track. Do not commit the raw feed.",
    sources: [
      {
        label: "BODS London GTFS",
        href: "https://data.bus-data.dft.gov.uk/timetable/download/gtfs-file/london/",
      },
    ],
  },
  {
    record: "PatternPathMatch",
    classification: "fetch",
    origin: "api-native",
    cachedIn: "none",
    refresh: "manual",
    coverage: "Underground, DLR, Tram, Cable Car",
    summary: "Which track a passenger pattern follows. Not joined yet.",
    note: "BODS trips.txt already links a trip to shape_id and a stop sequence. Persist that assignment after ingestion.",
    sources: [
      {
        label: "BODS London GTFS",
        href: "https://data.bus-data.dft.gov.uk/timetable/download/gtfs-file/london/",
      },
    ],
  },
  {
    record: "PatternPathMatch",
    classification: "process",
    origin: "processed",
    cachedIn: "none",
    refresh: "n/a",
    coverage: "Elizabeth line, Overground",
    summary: "Which track a passenger pattern follows. Not joined yet.",
    note: "A name-sequence matcher exists. Nothing is stored 1:1 yet.",
    sources: [{ label: "lib/tfl/cross-source-pattern-matching.ts" }],
  },
  {
    record: "PermittedMovement",
    classification: "process",
    origin: "processed",
    cachedIn: "none",
    refresh: "live",
    summary: "Which ways a train can continue through a junction.",
    note: "Inferred at request time from consecutive station triples on TfL patterns and OSM variants. Not persisted.",
    sources: [{ label: "lib/tfl/geometry/topology-movements.ts" }],
  },
  {
    record: "MapProductPolicy",
    classification: "author",
    origin: "authored",
    cachedIn: "none",
    refresh: "n/a",
    summary: "Which patterns belong on a carriage map, a platform map, the Tube map, or the geographic map.",
    note: "No feed decides which pattern belongs on a carriage, platform, Tube map, or geographic map.",
  },
  {
    record: "SourceSnapshot",
    classification: "process",
    origin: "authored",
    cachedIn: "this-repo",
    refresh: "manual",
    summary: "Where a snapshot came from, and when.",
    note: "This registry. Attach publisher, retrieval date, and validity to every derived snapshot.",
    sources: [{ label: "lib/tfl/network-model/status.ts" }],
  },
] as const
