import type { SourceSnapshot } from "@/lib/tfl/network-model/types"

/**
 * Inventory of each network-model record: where it comes from, where it is cached,
 * and how it refreshes. The Data model docs page renders this array directly.
 */
export const NETWORK_MODEL_STATUS: readonly SourceSnapshot[] = [
  {
    record: "Line",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "Name, colour, and mode for each line.",
    note: "Line identity, colour, and mode come from TfL line records shipped with tfl-ts.",
    sources: [{ label: "tfl-ts line metadata" }],
    usedOn: "all-four",
  },
  {
    record: "Station",
    classification: "process",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "A station’s identity and coordinates.",
    note: "NaPTAN ids and coordinates exist. Upgrade path: TfL station-data GTFS stops.txt for a stored station, platform, and OSM crosswalk.",
    sources: [
      { label: "tfl-ts STATION_HUBS" },
      {
        label: "TfL station-data GTFS",
        href: "https://api.tfl.gov.uk/stationdata/tfl-stationdata-gtfs.zip",
      },
    ],
    usedOn: "all-four",
  },
  {
    record: "StationHub",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "Stations that count as one interchange.",
    note: "Interchange grouping is already in STATION_HUBS. TfL station-data GTFS parent_station is the same id scheme.",
    sources: [
      { label: "tfl-ts STATION_HUBS" },
      {
        label: "TfL station-data GTFS",
        href: "https://api.tfl.gov.uk/stationdata/tfl-stationdata-gtfs.zip",
      },
    ],
    usedOn: "all-four",
  },
  {
    record: "ServicePattern",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "The ordered stations a service calls at.",
    note: "Ordered routes and service types ship as LINE_STATION_SEQUENCES. Enough for the carriage map, the platform map, and the Tube map.",
    sources: [{ label: "tfl-ts LINE_STATION_SEQUENCES" }],
    usedOn: "all-four",
  },
  {
    record: "PatternCall",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "tfl-ts",
    refresh: "build-time",
    summary: "One stop on a pattern, in order.",
    note: "Stop sequence is present on each static ordered route. Times are not stored here.",
    sources: [{ label: "tfl-ts LINE_STATION_SEQUENCES" }],
    usedOn: "all-four",
  },
  {
    record: "PatternCalendar",
    classification: "process",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    coverage: "Underground, DLR, Tram, Cable Car, Elizabeth line, Overground",
    summary: "Which days a pattern typically runs.",
    note: "Not required to draw the four maps. Kept only as an inspect overlay for skip-typicality. Rebuild with pnpm network-model:snapshot.",
    sources: [
      {
        label: "Aubin / Transitous GB GTFS",
        href: "https://beta.aubin.app/gtfs/great_britain_gtfs.zip",
      },
      { label: "data/network-model/ORIGIN.md" },
    ],
  },
  {
    record: "PatternFrequency",
    classification: "process",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    coverage: "Underground, DLR, Tram, Cable Car, Elizabeth line, Overground",
    summary: "How often a pattern typically runs.",
    note: "Not required to draw the four maps. How often a pattern runs does not change station order or track. Kept only as an inspect overlay.",
    sources: [
      {
        label: "Aubin / Transitous GB GTFS",
        href: "https://beta.aubin.app/gtfs/great_britain_gtfs.zip",
      },
      { label: "data/network-model/ORIGIN.md" },
    ],
  },
  {
    record: "PhysicalPath",
    classification: "process",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    coverage: "OSM unique-track (all rail modes)",
    summary: "Simplified track geometry. Geographic map only.",
    note: "Centreline, dual, and graph snapshots live under data/geography/unique-track. Rebuild with pnpm geography:unique-track. Default map paint is the preview LOD.",
    sources: [
      { label: "data/geography/ORIGIN.md" },
      { label: "Map – Tube & Rail (Geo)", href: "/docs/map-geographic" },
    ],
    usedOn: "geographic",
  },
  {
    record: "PhysicalPath",
    classification: "process",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    coverage: "Elizabeth line, Overground (timetable shapes)",
    summary: "Low-resolution line geometry from the timetable, for those two modes only.",
    note: "Not required to draw the geographic map. OSM unique-track already covers Elizabeth line and Overground. Kept as an inspect overlay.",
    sources: [
      {
        label: "Aubin / Transitous GB GTFS",
        href: "https://beta.aubin.app/gtfs/great_britain_gtfs.zip",
      },
      { label: "data/network-model/ORIGIN.md" },
    ],
  },
  {
    record: "PatternPathMatch",
    classification: "process",
    origin: "processed",
    cachedIn: "none",
    refresh: "n/a",
    coverage: "Underground (89/96 relations), Tram (8/10), DLR (5/12)",
    summary: "Which OSM track a passenger pattern follows.",
    note: "Aubin trips for these modes have empty shape_id, so this never comes from GTFS. Matched by OSM route-relation stop membership (ordered stop names on the relation), not by snapping station points onto nearby track — proximity snapping mis-assigns stations at shared-track stretches such as Waterloo & City, which this method matches to exactly its own two stops. Remaining gaps are name-normalisation mismatches (e.g. \"Custom House (for ExCel)\" vs OSM's \"Custom House for Excel\") and lines built after the pinned tfl-ts LINE_STATION_SEQUENCES snapshot (Northern line Battersea Power Station extension), not proximity errors. Cable car has no cached OSM route relation yet.",
    sources: [
      { label: "data/geography/ORIGIN.md" },
      { label: "data/geography/osm-cache" },
      { label: "lib/tfl/geometry/osm-pattern-path-match.ts" },
      { label: "lib/tfl/cross-source-pattern-matching.ts" },
    ],
    usedOn: "geographic",
  },
  {
    record: "PatternPathMatch",
    classification: "sufficient",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    coverage: "Elizabeth line, Overground",
    summary: "Which track a passenger pattern follows.",
    note: "Not required to draw the geographic map. Prefer OSM route-relation membership over a timetable shape_id.",
    sources: [
      {
        label: "Aubin / Transitous GB GTFS",
        href: "https://beta.aubin.app/gtfs/great_britain_gtfs.zip",
      },
      { label: "data/network-model/ORIGIN.md" },
    ],
  },
  {
    record: "PermittedMovement",
    classification: "process",
    origin: "processed",
    cachedIn: "this-repo",
    refresh: "manual",
    summary: "Which ways a train can continue through a junction.",
    note: "Derived from consecutive TfL station triples on LINE_STATION_SEQUENCES. The Aubin snapshot is an inspect overlay, not the map input.",
    sources: [
      { label: "tfl-ts LINE_STATION_SEQUENCES" },
      { label: "lib/tfl/geometry/topology-movements.ts" },
    ],
    usedOn: "all-four",
  },
  {
    record: "MapProductPolicy",
    classification: "author",
    origin: "authored",
    cachedIn: "none",
    refresh: "n/a",
    summary: "Which patterns belong on a carriage map, a platform map, the Tube map, or the geographic map.",
    note: "No feed decides which pattern belongs on a carriage, platform, Tube map, or geographic map.",
    usedOn: "all-four",
  },
  {
    record: "SourceSnapshot",
    classification: "process",
    origin: "authored",
    cachedIn: "this-repo",
    refresh: "manual",
    summary: "Where a snapshot came from, and when.",
    note: "This registry plus data/network-model/manifest.json (publisher, feed dates, agency allow-list). Rebuild with pnpm network-model:snapshot.",
    sources: [
      { label: "lib/tfl/network-model/status.ts" },
      { label: "data/network-model/ORIGIN.md" },
    ],
  },
] as const
