/**
 * Generate checked-in branch schematics from tfl-ts LINE_STATION_SEQUENCES.
 *
 * Writes a horizontal map and a vertical map per line. They are different
 * branch-to-lane assignments — do not rotate one graph.
 *
 * Run via `pnpm schematics:build`. Do not hand-edit files under
 * `lib/tfl/fixtures/generated/`.
 */

import { mkdirSync, readdirSync, unlinkSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { buildBranchSchematic } from "../lib/tfl/branch-schematic-layout.ts"
import { listBranchedLineIds } from "../lib/tfl/line-topology.ts"
import type {
  LineSchematic,
  SchematicOrientationHint,
} from "../lib/tfl/line-schematic.ts"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, "..")
const OUT_DIR = join(ROOT, "lib/tfl/fixtures/generated")
const BARREL_PATH = join(ROOT, "lib/tfl/branch-schematics.ts")
const ORIENTATIONS = ["horizontal", "vertical"] as const

const exportName = (
  lineId: string,
  orientation: SchematicOrientationHint
): string => {
  const slug = lineId
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
  return `${slug}_BRANCH_SCHEMATIC_${orientation.toUpperCase()}`
}

const fileName = (
  lineId: string,
  orientation: SchematicOrientationHint
): string => `${lineId}-branch-schematic-${orientation}.ts`

const printValue = (value: unknown, indent: number): string => {
  const pad = "  ".repeat(indent)
  const inner = "  ".repeat(indent + 1)
  if (value == null) return "undefined"
  if (typeof value === "string") return JSON.stringify(value)
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value)
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]"
    const items = value.map((item) => `${inner}${printValue(item, indent + 1)}`)
    return `[\n${items.join(",\n")},\n${pad}]`
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, item]) => item !== undefined
    )
    if (entries.length === 0) return "{}"
    const fields = entries.map(
      ([key, item]) => `${inner}${key}: ${printValue(item, indent + 1)}`
    )
    return `{\n${fields.join(",\n")},\n${pad}}`
  }
  return JSON.stringify(value)
}

const writeSchematicFile = (
  lineId: string,
  orientation: SchematicOrientationHint,
  schematic: LineSchematic
): void => {
  const name = exportName(lineId, orientation)
  const body = `// GENERATED by scripts/build-branch-schematics.ts — do not hand-edit.
// Source: tfl-ts LINE_STATION_SEQUENCES pinned in package.json.

import type { LineSchematic } from "@/lib/tfl/line-schematic";

export const ${name}: LineSchematic = ${printValue(schematic, 0)};
`
  writeFileSync(join(OUT_DIR, fileName(lineId, orientation)), body)
}

/** Northern's VERTICAL map is still hand-authored — vertical is out of scope for the topology clip. */
const usesHandVertical = (
  id: string,
  orientation: SchematicOrientationHint
): boolean => id === "northern" && orientation === "vertical"

const writeBarrel = (lineIds: readonly string[]): void => {
  const generatedImports = lineIds.flatMap((id) =>
    ORIENTATIONS.filter(
      (orientation) => !usesHandVertical(id, orientation)
    ).map(
      (orientation) =>
        `import { ${exportName(id, orientation)} } from "@/lib/tfl/fixtures/generated/${id}-branch-schematic-${orientation}";`
    )
  )

  const recordEntries = (orientation: SchematicOrientationHint): string =>
    lineIds
      .map((id) => {
        if (usesHandVertical(id, orientation)) {
          return `  northern: NORTHERN_LINE_SCHEMATIC_VERTICAL,`
        }
        return `  ${JSON.stringify(id)}: ${exportName(id, orientation)},`
      })
      .join("\n")

  const body = `import type { LineSchematic } from "@/lib/tfl/line-schematic";
import { NORTHERN_LINE_SCHEMATIC_VERTICAL } from "@/lib/tfl/fixtures/northern-line-schematic-vertical";
${generatedImports.join("\n")}

/**
 * Demo / docs registries.
 *
 * Northern, District, and Metropolitan's HORIZONTAL strips come from the
 * topology \u2192 energy \u2192 clip-to-grid path
 * (lib/tfl/geometry/branch-strip-from-topology.ts) \u2014 see
 * branch-schematic-layout.ts's TOPOLOGY_CLIP_LINE_IDS. Northern's VERTICAL
 * map is still the hand-authored fixture (vertical is out of scope for that
 * pass). Every other line/orientation is generated (\`pnpm schematics:build\`).
 * Horizontal and vertical maps are separate \u2014 do not rotate one graph.
 */
export const BRANCH_SCHEMATICS_HORIZONTAL: Record<string, LineSchematic> = {
${recordEntries("horizontal")}
};

export const BRANCH_SCHEMATICS_VERTICAL: Record<string, LineSchematic> = {
${recordEntries("vertical")}
};

export const BRANCH_SCHEMATICS = BRANCH_SCHEMATICS_HORIZONTAL;

export const BRANCH_SCHEMATIC_LINE_IDS = Object.keys(BRANCH_SCHEMATICS_HORIZONTAL);
`
  writeFileSync(BARREL_PATH, body)
}

const main = (): void => {
  mkdirSync(OUT_DIR, { recursive: true })
  const generated: string[] = []
  const written = new Set<string>()

  for (const lineId of listBranchedLineIds()) {
    let wroteAny = false
    for (const orientation of ORIENTATIONS) {
      try {
        const schematic = buildBranchSchematic(lineId, orientation)
        if (!schematic) {
          console.warn(`skip ${lineId} ${orientation}: no topology`)
          continue
        }
        writeSchematicFile(lineId, orientation, schematic)
        written.add(fileName(lineId, orientation))
        wroteAny = true
        console.log(
          `wrote ${fileName(lineId, orientation)} (${schematic.nodes.length} nodes)`
        )
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        console.warn(`skip ${lineId} ${orientation}: ${message.split("\n")[0]}`)
      }
    }
    if (wroteAny) generated.push(lineId)
  }

  for (const existing of readdirSync(OUT_DIR)) {
    if (!existing.endsWith(".ts")) continue
    if (written.has(existing)) continue
    unlinkSync(join(OUT_DIR, existing))
    console.log(`removed stale ${existing}`)
  }

  writeBarrel(generated)
  console.log(
    `barrel ${generated.length} lines × 2 → lib/tfl/branch-schematics.ts`
  )
}

main()
